### ISSUE TITLE
Gjeninnføre den særskilte lærlingeordningen åpner for nye tilfeller  fra virkning xx tom 28. februar

### ISSUE THREAD

**Issue by rannveigskjerve** [navikt/dagpenger#1006]
- [x] dp-regel-sats? nA se #1000 
- [x] dp-regel-grunnlag? nA se #1000 
- [x] navikt/dp-regel-minsteinntekt#42
- [x] navikt/dp-regel-periode#38 
- [x] ~~søknadsdialog, husk gjennopptak~~ Ingen endring
- [x] ~~dp-mottak (ruting)~~ Ingen endring, lærling har ingen spesiell ruting
- [x] ~~dagpengekalkulator (tekst)~~
- [x] ~~dp-quiz: sjekk at lærling sendes til manuell~~ingen endring

**Comment by geiralund** [comment]
DONE!
