### ISSUE TITLE
Gjeninnføre redusert krav til minsteinntekt. Inngangsvilkår for dagpenger settes ned til 0,75 G siste 12 måneder eller 2,25 G siste 36 måneder, når dette er mulig er mulig å gjennomføre for Nav. Ordningen gis virkning tom &nbsp;28. februar.

### ISSUE THREAD

**Issue by rannveigskjerve** [navikt/dagpenger#1007]
- [x] navikt/dp-regel-minsteinntekt#42
- [x] kalkulator: navikt/dp-faktasider-frontend#187
   (NB: Uinlogget kalk er fjernet av innholdteamet midlertidig, frem til gjeninføring av nye terskelverdier)
- [x] ~~sjekk dp-soknad-frontend tekster, info om EØS perioder?~~ Ref Eivind sin kommentar, ingen endring nødvendig
- [x] dp-quiz: navikt/dp-quiz#40

**Comment by EivindRoyrvik** [comment]
Quiz: automatiske avslag tenker jeg vi uansett bør vente med å skru på igjen før ny virkningsdato er passert

EØS: Det gis kun generell informasjon i søknaden, ikke spesifikk info som må endres. 

Lærling: Alternativet om lærling ligger fortsatt inne under arbeidsforhold 
![image](https://user-images.githubusercontent.com/82581338/145984068-a12b718d-f9ad-4d97-bcca-4657b8eed979.png)

**Comment by gtcno** [comment]
Ingen tekster trenges å endre i dp-soknad-server/frontend

**Comment by geiralund** [comment]
DONE!
