### ISSUE TITLE
dp-regel-api Avvikle fangst og fisk

### ISSUE THREAD

**Issue by greger-nl** [navikt/dagpenger#1013]
- [x] Legge særregel bak regelverksdatosjekk i
  - [x] navikt/dp-regel-minsteinntekt#43 --> Klar for prod
  - [x] navikt/dp-regel-grunnlag#47 --> Klar for prod
  - [x] navikt/dp-regel-periode#37 --> Klar for prod
  - [x] ~~dp-regel-sats~~ Ingen endring nødvendig.
  - [x] ~~dp-*inntekt~~ Ingen endring nødvendig.
  - [x] ~~Vi må også gjøre en vurdering av hva vi gjør med innhenting av inntekt fordi vi ikke vet på tidspunktet vi innhenter inntekt hvilket virkningstidspunkt vedtaket skal ha???~~ -Her har vi ikke gjort noe, inntektskomponenten får alltid med fangst og fisk

**Comment by geiralund** [comment]
DONE~!
