### ISSUE TITLE
Legge til rapids-and-rivers behov app for dp-regel-sats

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#376]
For å kunne bruke de eksisterende reglene for minsteinntekt, grunnlag og sats bør de kunne kalles via rapid/rivers-modellen.

Raskeste vei til mål er å bygge en liten tjeneste som prater rapid/river og kjører reglene via `dp-regel-api`.

**Comment by androa** [comment]
Jeg tror det er veldig vanskelig/uheldig å få `dp-saksbehandling` til å prate det gamle Behov-formatet.

Det beste hadde vært om man kunne bruke det nye Behov-formatet. Jeg tror vi kan gjøre det på forskjellige måter:

1. Kjøre to "apps" i hver av regel-tjenestene. En med den gamle, og en annen med den nye. Det blir noen dumme ting som ktor-servere og helsesjekker.
2. Samme som over, men prøve å dele det i to deployments.
3. Bygge en ny tjeneste som lytter på Behov og bruker `dp-regel-api` til å prate med de gamle reglene via HTTP.

**Comment by androa** [comment]
Konsensus i diskusjonen på Slack tilsier at det raskeste er alternativ 3. Omformulerer issuet til å beskrive den jobben.

**Comment by androa** [comment]
Et alternativ 4:

Lage en egen release branch hvor appen byttes ut med en rivers-and-rapids app og rebase den på master når vi gjør endringer i reglene.

Det gjør det mulig å håndtere det som to ulike deployments med ulik livssykluser, ulike artifacts, og nais.yamler med relativ lav risiko for å gå i beina på de reglene Arena er avhengig av.

**Comment by androa** [comment]
Prøvde alternativ 1 på `dp-regel-sats` her https://github.com/navikt/dp-regel-sats/pull/14, det ser ikke ut som det ble så veldig hårete.

**Comment by androa** [comment]
https://github.com/navikt/dp-regel-sats/pull/14 viste seg å bli ganske bra.

Oppretter egne tasks for alle de andre tjenestene:

- [x] [dp-regel-minsteinntekt](/navikt/dp-regel-minsteinntekt) - https://github.com/navikt/dp-regel-minsteinntekt/issues/32
- [x] [dp-regel-periode](/navikt/dp-regel-periode) - https://github.com/navikt/dp-regel-periode/issues/23
- [x] [dp-regel-grunnlag](/navikt/dp-regel-grunnlag) - https://github.com/navikt/dp-regel-grunnlag/issues/37
- [x] [dp-inntekt-klassifiserer](/navikt/dp-inntekt-klassifiserer) - https://github.com/navikt/dp-inntekt-klassifiserer/issues/8

Glemte jeg noen her da?
