### ISSUE TITLE
Beregningsdato må med i ferdigstilte_dagpengegrunnlag

### ISSUE THREAD

**Issue by espenjohansen** [navikt/dagpenger#663]
I  https://jira.adeo.no/browse/FAGSYSTEM-140183 er det meldt feil med at inntekter ikke vises - gir feilen "404 Kunne ikke finne inntekt i databasen"

Årsaken til dette ser ut til å være at beregningsdato har vært endret på tidligere vedtak i forhold til det som vi har har lagret i DD. 

Ifølge Mona Kjeldrud vil dette kunne løses ved å gjøre nevnte endring. Melder også over sak https://jira.adeo.no/browse/ARENA-5129 for nødvendig  endring i Arena.

**Comment by magnefjeld** [comment]
Har snakket litt med Espen om denne. Vi har konkludert med at vi ber arena-leverandør kaller oss inn til et møte her. Videresender innkalling, når den kommer, til de som skal være med her.

Spørsmålet her er om denne kan ha et nedslagsfelt/avhengighet til flere saker,  som må vurderes sett på/vurdert, samtidig:

- [ ] https://github.com/navikt/dagpenger/issues/565  - Endre logikk for fastsettelse av dagpengegrunnlag for vernepliktige dersom det skal innvilges for tidsrom med gammel G 
- [ ] https://github.com/navikt/dagpenger/issues/566 - Beregning av Grunnlag og sats når Verneplikt må ta hensyn til beregningsdato
- [ ] https://github.com/navikt/dagpenger/issues/575 - Før 1. oktober 2021: Behov for å skille mellom virkningstidspunkt og beregningsdato


For sistnevnte https://github.com/navikt/dagpenger/issues/575 , er det allerede tidligere i 2020 gjennomført møter med leverandør, og blitt analysert, men er ikke endelig landet hvordan VI ønsker: 

- [ ] https://confluence.adeo.no/pages/viewpage.action?pageId=377185785 
- [ ] https://confluence.adeo.no/display/TEAMARENA/ARENA-4582+01+-+Dokumentinformasjon

**Comment by magnefjeld** [comment]
se https://jira.adeo.no/browse/ARENA-5129 . Arenaleverandør har gjort en kort analyse av problemstillingen. Kan dere se over om dette er tilfredstillende for oss, eventuelt hvilke tilpasninger vi må gjøre på vår side?

I tillegg. Når espen og jeg opprettet oppgaven var vi litt usikre på om denne saken kunne ha nedslagsfelt til 565,566 og 575. For meg virker det ikke slik ved første blikk på analysen. Men det er fint om det vurderes om det har nedslagsfelt til disse andre sakene.

**Comment by rannveigskjerve** [comment]
Vi tror egentlig at dette kan løses fra vår side med å endre spørring til db  fra `eksakt dato` til `innenfor registreringsperiode`. Men dette må avklares med resten av teamet.

**Comment by magnefjeld** [comment]
@rannveigskjerve takk. Tar du det med resten av teamet, hva dere anbefaler som løsning, så tilbakemelder jeg til arena-leverandør.

**Comment by rannveigskjerve** [comment]
Foreslått løsning vil fungere, men har noen bieffekter. Lukker dette issuet. Kan gjenåpnes hvis dette viser seg å bli et hyppig problem.
