### ISSUE TITLE
Gi forhøyet dagsats også til personer innvilget dagpenger før 20.mars 2020 - 1. mai

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#685]
19.02.21 https://lovdata.no/dokument/LTI/forskrift/2021-02-19-473 :

**§ 2-3 nytt tredje ledd skal lyde:

Medlemmer som har fått innvilget dagpenger med virkningstidspunkt før 20. mars 2020, og som har rett til dagpenger per 1. februar 2021, får beregnet dagpengene etter første ledd fra og med 1. februar 2021.**
-----

Stortinget vedtok 18.02.21: Stortinget ber regjeringen endre dagpengereglene slik at personer som fikk innvilget dagpenger før 20. mars 2020, fra 1. februar 2021 får økte satser lik den midlertidig forhøyede dagpengesatsen.

Arenasak: https://jira.adeo.no/browse/ARENA-5370 

Gjenstår:

- [x] Snakke med mona om parametere i respons
- [x] regelverksdato og forrige grunnlag i respons til arena
- [x] Endre api-docs

Kan ryddes:
- [x] beregningsregel ligger både i resultat-blokken og inne i grunnlag-blokken. Arena benytter bare den som ligger inne i grunnlag-blokken

**Comment by magnefjeld** [comment]
Gjennomført møte: Ref https://github.com/navikt/dagpenger/issues/682

**Comment by magnefjeld** [comment]
Her må vi analysere og estimere og komme tilbake til team Arena
t.o @atleno @rannveigskjerve

**Comment by magnefjeld** [comment]
Denne har et nedslagsfelt/avhengighet til flere saker, som må vurderes sett på/vurdert, samtidig:

- [x]  #565 - Endre logikk for fastsettelse av dagpengegrunnlag for vernepliktige dersom det skal innvilges for tidsrom med gammel G (duplikat)

- [x]  #566 - Beregning av Grunnlag og sats når Verneplikt må ta hensyn til beregningsdato

 

- [x] #575 - Før 1. oktober 2021: Behov for å skille mellom virkningstidspunkt og beregningsdato

For sistnevnte #575 , er det allerede tidligere i 2020 gjennomført møter med leverandør, og blitt analysert, men er ikke endelig landet hvordan VI ønsker:

 https://confluence.adeo.no/pages/viewpage.action?pageId=377185785
 https://confluence.adeo.no/display/TEAMARENA/ARENA-4582+01+-+Dokumentinformasjon

**Comment by magnefjeld** [comment]
Videsendt innkalling til møte 3. mars 2021. https://confluence.adeo.no/pages/viewpage.action?pageId=402567014 
smart å gå igjennom analysen og åpne punkter før møtet. t.o @atleno @rannveigskjerve @urenhale

**Comment by magnefjeld** [comment]
opprettet https://jira.adeo.no/browse/ARENA-5495 etter ønske fra Mona.

**Comment by magnefjeld** [comment]
https://confluence.adeo.no/display/TEAMARENA/2021-EL03+Arena+leveranse er planlagt 24.3.21

**Comment by magnefjeld** [comment]
vært møte 3.3.21. @atleno var med på deler av møtet. Avklart at vi setter opp et fot-i-bakken møte på fredag 5.3.21. 
Arena-leverandør har kalt inn til oppstartsmøte mandag 8. mars 2021 om https://jira.adeo.no/browse/ARENA-5495

Det som er et forretningskrav:
- Ikke hentes inntekter på nytt
- Ikke fastsette/beregne grunnlag på nytt.

når vi skal gi forhøyet dagsats fra og med 1.2.21, til de med dagpengevedtak fra før 20.3.20.

Det ble diskutert ulike alternativer på møtet, men vi har allerede https://jira.adeo.no/browse/ARENA-5495 oversendt til leverandør. Spørsmålet er da om vi skal gjøre endring i endepunktet eller om vi skal lage nytt. Det må vi ha tatt stilling til før fredagens møte.

**Comment by magnefjeld** [comment]
@atleno @rannveigskjerve @urenhale 
https://jira.adeo.no/browse/ARENA-5495 løsningsbeskrivelse er klar til godkjenning. Fint om dere starter å se på den og gi tilbakemelding om ok/ikke ok .

**Comment by rannveigskjerve** [comment]
> @atleno @rannveigskjerve @urenhale
> https://jira.adeo.no/browse/ARENA-5495 løsningsbeskrivelse er klar til godkjenning. Fint om dere starter å se på den og gi tilbakemelding om ok/ikke ok .

Det ser bra ut!

**Comment by magnefjeld** [comment]
satt opp møte torsdag 25.3.21, for å se litt på hvordan vi skal løse ulike type scenarioer, hvor regelverksdato ikke kan settes slik at 12/36 treffer riktig. Dette treffer i hovedsak minsteinntekt. Vi snakker mer om det 25.3.21.
