### ISSUE TITLE
Søknadsdialogen - Veiledningstekster mv- Reversere tilbake til pre-corona . 1. oktober 2021

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#828]
De aller fleste midlertidige regler på dagpengeområdet skal opphøre fra 1. oktober 2021. Det må da gjøres flere endringer i søknadsdialogen, som må implementeres fra 1. oktober 2021 (primært er dette tekstlige endringer):

- [x] Ventetid på 3 dager gjeninnføres (innført på https://github.com/navikt/dagpenger/issues/654)
- [x] Terskelkrav på 50 % gjeninnføres (unntak for FISK)  (innført på https://github.com/navikt/dagpenger/issues/671)
- [x] Avbruddsperioden tilbake til 6 uker (innført på https://github.com/navikt/dagpenger/issues/777)

Det vil bli laget egne kort for (som er mer enn bare tekstlige endringer/endringer utenfor søknadsdialogen):
- [x] Utdanning (nytt søknadsskjema og endringer i dagens søknadsdialog må taktes.) (https://github.com/navikt/dagpenger/issues/831)
- [x] Avvikle fortsatt rett (https://github.com/navikt/dagpenger/issues/827)
- [x] https://github.com/navikt/dagpenger/issues/897

**KAN IKKE DEPLOYES FØR 01.10.2021**

**Comment by magnefjeld** [comment]
https://confluence.adeo.no/pages/viewpage.action?pageId=377177138 gir mer mer informasjon om de ulike endringene NAV leverer (samleoversiktsside) på dagpengeområdet.

**### Overordnet er det følgende endringer (ikke alle treffer oss i digidag):**

_- Ventedager tilbake til precovid-19 regler ​
 
- Minsteinntekt tilbake til precovid-19 regler  ​
 
- Avvikling av midlertidige regler for halv føring av timer på meldekort for enkelte yrker ​
 
- Terskel/gradering tilbake til precovid-19 regler  ​
 
- Avbruddsperioden tilbake til mer enn seks uker.​
 
- Forlengelser opphører ​
 
- Avvikling av fortsatt rett ​
 
- Avvikling av lærlingeordningen for nye tilfeller (opphører i sin helhet fra 1. januar 2022) ​
 
- Avvikling av forhøyet sats_ 


Flere endringer til 1. oktober 2021 er allerede ivaretatt ved at at det satt til og med datoer hos digidag (og Arena) på flere av regelverksendringene. Dette gjelder minsteinntekt, beregning og sats, samt lærlingeordningen (sistnevnte avblendes i Arena når man setter virkningstidspunkt 1. oktober 2021 eller senere på ny rettighet.) Dette innebærer at disse allerede nå kan testet til leveransen.

Endringene vi skal gjøre i søknadsdialogen tester vi selv og har ikke noen direkte avhengighet til andre. Unntaket er endringene knyttet til utdanning, som må taktes mot innholdsteamet (primært knut) og chris. Chris ser på dette og de kommer tilbake til oss.

Foreløpig er det vi må se på avvikling av forhøyet sats, om det er noe mer vi må gjøre der knyttet til den automatiske konverteringen Arena skal gjøre til 1. oktober 2021 (til ordinær sats).

Ellers skal det ikke være noen store oppgaver rundt dette, med mindre det er noe vi ikke har forutsett, som oppdages under testing (og hypotesen er at det primært vil kunne treffe avvikling av forhøyet sats)

t.o @Elinvethe @androa
