### ISSUE TITLE
Avvikle fangst og fisk når virkningstidspunkt er 1.1.2022 (§4-18)

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#947]
Gitt at virkningstidspunkt er 1.1.2022 eller senere så skal vi ikke inkludere inntekt fra fangst og fisk (Lott) i beregning av minsteinntekt, dagpengeperiode, dagpengegrunnlag eller sats

Ta kontakt med @Elinvethe dersom dere er usikre, spesielt hvis man ikke er kjent med hvilke inntekter som menes med "fangst og fisk" eller om det er uklart hva skjæringspunktet for når fangst og fisk skal inkluderes og når det ikke skal inkluderes

I dag innhenter vi inntekter om fangst og fisk og vi inkluderer det i beregning av minsteinntekt, dagpengeperiode, dagpegnegrunnlag og sats dersom Arena gir beskjed om at vedtaksfakta for fangst og fisk er "true".  For vedtak som har virkningstidspunkt 1.1.2022 skal Arena slutte å sende oss true på vedtaksfakta for fangst og fisk. Dere kan lese mer om løsningsbeskrivelsen fra Arena her: https://confluence.adeo.no/pages/viewpage.action?pageId=432218018

NB! **Hyre** skal fortsatt være med, det er kun **Lott** som skal ut

- [x] Fjerne valget i søknaden
  - [x]  Frontend: navikt/dp-soknad-frontend#69
  - [x] Backend: navikt/dp-soknad-server#160
- [x]  navikt/dp-kalkulator-frontend#354
- [x] ~~Fjerne sjekken som sender til manuell i dp-quiz~~ Oppryddningsjobb av død kode, gjøres på et senere tidspunkt.
- [x] navikt/dagpenger#1013
